### ISSUE TITLE
界面上多了个button按钮

### ISSUE THREAD

**Issue by jiangood** [991233liu/STK#1]
另外这个界面高度，透明度怎么调整的，没找到方法

**Comment by 991233liu** [comment]
调试按钮已经删掉，下载新版本即可。
下载地址：https://gitee.com/liulufeng/stk/releases/tag/0.2.1.11

**Comment by 991233liu** [comment]
调试按钮已经删掉，下载新版本即可。
下载地址：https://gitee.com/liulufeng/stk/releases/tag/0.2.1.11
